user www-data;
worker_processes auto;

events {
    worker_connections 1024;
}

http {

    ## Basic Settings
    sendfile on;
    tcp_nopush on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    ## Logging
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    ## Compression
    gzip on;

    ## Load modular configuration files
    include /etc/nginx/conf.d/rate-limit.conf;
    include /etc/nginx/conf.d/reverse-proxy.conf;
    include /etc/nginx/conf.d/ssl.conf;

}